# Port that the hub will listen for server (gRPC) connections
GrpcPort: 5085
# Port that the hub will listen on for the web interface
HttpPort: 8000
# Filename of main logo in wwwroot/images
MainLogoFile: logo.svg
# Filename of logo shown in nav bar in wwwroot/images
NavbarLogoFile: logo.svg
# Name of the hub, will be shown in web page titles
HubName: Future Crew
# Minimum client security level for lap times to be considered valid
MinimumClientSecurityLevel: 0
# List of keys that are allowed to connect to the hub. Do not share these keys with other people!
Keys:
- Key: K8BM4Y2YF+jnD3LYwv4aoRe389pEUt7adm0WdXMhhN0=
  Name: SRP
- Key: OX4FSe2o9SpfylqM19HRUZAyK6MaxhwvLG0uRls3nRc=
  Name: Horizon
- Key: XfvFBKBTMOrBKYvTv3M4m7vpGtgLCS1egHt9YxGWpgE=
  Name: None DLC
- Key: eEBFJTAjDMT9hzZL2J6yxs0C2GnbzJAX+kK8z66jvX8=
  Name: Freeroam
- Key: NFFfXgRNdv1lSgbBt6/Ll59MuiUZB57vVbx6cbZqXlM=
  Name: Nordschleife Tourist
- Key: bS/WS0vtOxKxYav/aFP+it8pwIG8xYsqacpwvQAYCr4=
  Name: JDM
- Key: aKSbtcHod6nSZqjFof2HHuUEGG8CzoSVlvqkQTg+T3U=
  Name: Manual
- Key: mUnbrqIm2+I2ONa91ydKW422u0YutX7yA4uR4qOjkLI=
  Name: EU Non DLC
- Key: 6UBNxhUHWpuopC7TW7BQdZkA9Hvclx9T89Fx6WYKoh0=
  Name: EU SRP
- Key: M0ESBU6VqDYFPMFAqcsI5m6lDiJYFuXMPzGUQwg3f6g=
  Name: Staff Server
- Key: 4ijsjSRTQCNRc4w9sjwRwNrQfsiJv9XyPCxupFh6n6U=
  Name: Spec
- Key: EXhCmXJz8DBevLwPPEg5nh4tJbi9P1Qcpa59TiS/T2w=
  Name: Cops and Robbers
- Key: rK1SInGMlAy/Rca5oMCNyyU5OKdIVQ16NfdPIvcoFes=
  Name: Drift SRP
- Key: ezEXpUZ89AkROdPpqlEkJA/vxCg6VDNWQnrEz4H2U5o=
  Name: Drift Park
- Key: VXWVZX/8X7FZQYeitsLADe7UBNMoJptqfDKwbLoS/aU=
  Name: Sandbox
- Key: eDCP0GCwuNpXnXIbHRNCzZ6132BXAWAF4/Rxc94t+X8=
  Name: Content Preview
- Key: MkHndj60Pvbsd0D1OujSP8aRt6OhT+WVDMrREzFxuM8=
  Name: Whiteline
- Key: x1d3LtRX6mtcOk3EdjTQtd58MUQQQQr0OHyHWhswC3k=
  Name: Hamburg Cops and Robbers
- Key: v4NJqWE8WBxW49Q3WcPOnywD+xmNxY36dJr9LTWGALY=
  Name: Hamburg Public
- Key: uHijawWq6CHSAfaB1ITcHk7s8MTQRBniPgdsV8xAP5Y=
  Name: German Cars
- Key: UD5RdHg9ipp/DSbmNjUljZSLmOdY3albi7mG3BB58vw=
  Name: FDR US
- Key: 5idOj12RR1Ydr/yewqk4h4pZmy+y+k1xg6p5R04dcVM=
  Name: FDR EU
# Discord Client ID
DiscordClientId: 1185813479832166470
# Discord Client Secret
DiscordClientSecret: 
# Discord Bot Token
DiscordBotToken: MTE4NTgxMzQ3OTgzMjE2NjQ3MA.G2Ec8t.rTWoppeIS_9GnbktP66az1c-BvRXjf0TK9-qGM
# List of Discord overtake leaderboard templates
DiscordOvertakeLeaderboardTemplates: {}
# List of Discord race challenge leaderboard templates
DiscordRaceChallengeLeaderboardTemplates: {}
# List of Discord timing leaderboard templates
DiscordTimingLeaderboardTemplates: {}
# List of Discord timing points leaderboard templates
DiscordTimingPointsLeaderboardTemplates: {}
# List of Discord timing stage leaderboard templates
DiscordTimingStageLeaderboardTemplates: {}
# List of Discord server status templates
DiscordServerStatusTemplates:
  emoji: "{{ for server in servers }}\n**{{ server.alias }}**\n{{\n  if server.online\n    fill = server.clients / server.max_clients\n    if fill < 0.5\n      \":green_circle:\"\n    else if fill < 0.75\n      \":yellow_circle:\"\n    else\n      \":orange_circle:\"\n    end\n    \" Online\"\n  else\n    \":red_circle: Offline\"\n  end\n  \n  timeSplit = server.time | string.split \":\"\n  hours = timeSplit[0] | string.to_int\n  minutes = timeSplit[1] | string.to_int\n  \n  if minutes >= 45\n    hours += 1\n  end\n  \n  hours = hours % 12\n  \n  if hours == 0\n    hours = 12\n  end\n  \n  if minutes > 15 && minutes < 45\n    minutes = 30\n  else\n    minutes = \"\"\n  end\n  \n  clockEmoji = \":clock\" + hours + minutes + \":\" \n}} · :busts_in_silhouette: `{{ server.clients | string.pad_left 2 }}/{{ server.max_clients | string.pad_left 2 }}` · {{ clockEmoji }} `{{ server.time }}` · **[Join]({{ server.invite }})**\n{{ end }}\n"
  SRP: "{{ for server in servers }}\n**{{ server.alias }}**\n{{\n  if server.online\n    fill = server.clients / server.max_clients\n    if fill < 0.5\n      onlineStatus = \":green_circle:\"\n    else if fill < 0.75\n      onlineStatus = \":yellow_circle:\"\n    else\n      onlineStatus = \":orange_circle:\"\n    end\n    \n    timeSplit = server.time | string.split \":\"\n    hours = timeSplit[0] | string.to_int\n    minutes = timeSplit[1] | string.to_int\n    \n    if minutes >= 45\n      hours += 1\n    end\n    \n    hours = hours % 12\n    \n    if hours == 0\n      hours = 12\n    end\n    \n    if minutes > 15 && minutes < 45\n      minutes = 30\n    else\n      minutes = \"\"\n    end\n    \n    clockEmoji = \":clock\" + hours + minutes + \":\"\n  else\n    onlineStatus = \":red_circle: Offline\"\n    clockEmoji = \"\" \n  end\n}} \n{{ onlineStatus }} **Public Slots:** {{ server.clients | string.pad_left 2 }}/{{ server.max_clients | string.pad_left 2 }}  \n**<:Tier3:1283467604098416661>** **VIP Slots:** 0/8\n  {{ clockEmoji }} {{ server.time }}\n**[ENTER SERVER HERE]({{ server.invite }})**\n{{ end }}\n"
  None DLC: "{{ for server in servers }}\n**{{ server.alias }}**\n{{\n  if server.online\n    fill = server.clients / server.max_clients\n    if fill < 0.5\n      onlineStatus = \":green_circle:\"\n    else if fill < 0.75\n      onlineStatus = \":yellow_circle:\"\n    else\n      onlineStatus = \":orange_circle:\"\n    end\n    \n    timeSplit = server.time | string.split \":\"\n    hours = timeSplit[0] | string.to_int\n    minutes = timeSplit[1] | string.to_int\n    \n    if minutes >= 45\n      hours += 1\n    end\n    \n    hours = hours % 12\n    \n    if hours == 0\n      hours = 12\n    end\n    \n    if minutes > 15 && minutes < 45\n      minutes = 30\n    else\n      minutes = \"\"\n    end\n    \n    clockEmoji = \":clock\" + hours + minutes + \":\"\n  else\n    onlineStatus = \":red_circle: Offline\"\n    clockEmoji = \"\" \n  end\n}} \n{{ onlineStatus }} **Public Slots:** {{ server.clients | string.pad_left 2 }}/{{ server.max_clients | string.pad_left 2 }}  \n  {{ clockEmoji }} {{ server.time }}\n**[ENTER SERVER HERE]({{ server.invite }})**\n{{ end }}\n"
  Horizon: "{{ for server in servers }}\n**{{ server.alias }}**\n{{\n  if server.online\n    fill = server.clients / server.max_clients\n    if fill < 0.5\n      onlineStatus = \":green_circle:\"\n    else if fill < 0.75\n      onlineStatus = \":yellow_circle:\"\n    else\n      onlineStatus = \":orange_circle:\"\n    end\n    \n    timeSplit = server.time | string.split \":\"\n    hours = timeSplit[0] | string.to_int\n    minutes = timeSplit[1] | string.to_int\n    \n    if minutes >= 45\n      hours += 1\n    end\n    \n    hours = hours % 12\n    \n    if hours == 0\n      hours = 12\n    end\n    \n    if minutes > 15 && minutes < 45\n      minutes = 30\n    else\n      minutes = \"\"\n    end\n    \n    clockEmoji = \":clock\" + hours + minutes + \":\"\n  else\n    onlineStatus = \":red_circle: Offline\"\n    clockEmoji = \"\" \n  end\n}} \n{{ onlineStatus }} **Public Slots:** {{ server.clients | string.pad_left 2 }}/{{ server.max_clients | string.pad_left 2 }}  \n**<:Tier3:1283467604098416661>** **VIP Slots:** 0/4\n  {{ clockEmoji }} {{ server.time }}\n**[ENTER SERVER HERE]({{ server.invite }})**\n{{ end }}\n"
  Nord: "{{ for server in servers }}\n**{{ server.alias }}**\n{{\n  if server.online\n    fill = server.clients / server.max_clients\n    if fill < 0.5\n      onlineStatus = \":green_circle:\"\n    else if fill < 0.75\n      onlineStatus = \":yellow_circle:\"\n    else\n      onlineStatus = \":orange_circle:\"\n    end\n    \n    timeSplit = server.time | string.split \":\"\n    hours = timeSplit[0] | string.to_int\n    minutes = timeSplit[1] | string.to_int\n    \n    if minutes >= 45\n      hours += 1\n    end\n    \n    hours = hours % 12\n    \n    if hours == 0\n      hours = 12\n    end\n    \n    if minutes > 15 && minutes < 45\n      minutes = 30\n    else\n      minutes = \"\"\n    end\n    \n    clockEmoji = \":clock\" + hours + minutes + \":\"\n  else\n    onlineStatus = \":red_circle: Offline\"\n    clockEmoji = \"\" \n  end\n}} \n{{ onlineStatus }} **Public Slots:** {{ server.clients | string.pad_left 2 }}/{{ server.max_clients | string.pad_left 2 }}  \n**<:Tier3:1283467604098416661>** **VIP Slots:** 0/4\n  {{ clockEmoji }} {{ server.time }}\n**[ENTER SERVER HERE]({{ server.invite }})**\n{{ end }}\n"
  Cops and Robbers: "{{ for server in servers }}\n**{{ server.alias }}**\n{{\n  if server.online\n    fill = server.clients / server.max_clients\n    if fill < 0.5\n      onlineStatus = \":green_circle:\"\n    else if fill < 0.75\n      onlineStatus = \":yellow_circle:\"\n    else\n      onlineStatus = \":orange_circle:\"\n    end\n    \n    timeSplit = server.time | string.split \":\"\n    hours = timeSplit[0] | string.to_int\n    minutes = timeSplit[1] | string.to_int\n    \n    if minutes >= 45\n      hours += 1\n    end\n    \n    hours = hours % 12\n    \n    if hours == 0\n      hours = 12\n    end\n    \n    if minutes > 15 && minutes < 45\n      minutes = 30\n    else\n      minutes = \"\"\n    end\n    \n    clockEmoji = \":clock\" + hours + minutes + \":\"\n  else\n    onlineStatus = \":red_circle: Offline\"\n    clockEmoji = \"\" \n  end\n}} \n{{ onlineStatus }} **Public Slots:** {{ server.clients | string.pad_left 2 }}/{{ server.max_clients | string.pad_left 2 }}  \n**<:Tier3:1283467604098416661>** **VIP Slots:** 0/6\n  {{ clockEmoji }} {{ server.time }}\n**[ENTER SERVER HERE]({{ server.invite }})**\n{{ end }}\n"
  VIP: "{{ for server in servers }}\n**{{ server.alias }}**\n{{\n  if server.online\n    fill = server.clients / server.max_clients\n    if fill < 0.5\n      onlineStatus = \":green_circle:\"\n    else if fill < 0.75\n      onlineStatus = \":yellow_circle:\"\n    else\n      onlineStatus = \":orange_circle:\" **[Purchase VIP](teamfuturecrew.wixsite.com/home/vip)** \n    end\n    \n    timeSplit = server.time | string.split \":\"\n    hours = timeSplit[0] | string.to_int\n    minutes = timeSplit[1] | string.to_int\n    \n    if minutes >= 45\n      hours += 1\n    end\n    \n    hours = hours % 12\n    \n    if hours == 0\n      hours = 12\n    end\n    \n    if minutes > 15 && minutes < 45\n      minutes = 30\n    else\n      minutes = \"\"\n    end\n    \n    clockEmoji = \":clock\" + hours + minutes + \":\"\n  else\n    onlineStatus = \":red_circle: Offline\"\n    clockEmoji = \"\" \n  end\n}} \n{{ onlineStatus }} **Public Slots:** {{ server.clients | string.pad_left 2 }}/{{ server.max_clients | string.pad_left 2 }}  \n  {{ clockEmoji }} {{ server.time }}\n**[ENTER SERVER HERE]({{ server.invite }})**\n{{ end }}\n"
# List of Discord server status widgets
DiscordServerStatus:
  SRP-status:
    Title: US Public
    Template: SRP
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: 1️⃣  Heavy Traffic I Public
      Address: 5.78.46.52:8081
    - Name: 2️⃣  Heavy Traffic I Public NON-DLC
      Address: 5.78.46.52:8080
  Horizon-status:
    Title: Horizon US
    Template: Horizon
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: Horizon | Dense Traffic
      Address: 5.78.103.54:8081
  Preview-status:
    Title: Content Preview
    Template: None DLC
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: Dense Traffic | Content Preview
      Address: 5.78.93.251:8081
  JDM-status:
    Title: Tier 2 JDM
    Template: emoji
    ThumbnailUrl: https://flagcdn.com/w2560/eu.png
    Color: '#003399'
    Servers:
    - Name: JDM Cars | Heavy Traffic
      Address: 5.78.113.173:8083
  Nord-status:
    Title: Nordschleife Tourist
    Template: Nord
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: Nordschleife 1
      Address: 5.78.103.54:8080
  Manual-status:
    Title: Manual
    Template: VIP
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: Heavy Traffic | Manual Cars
      Address: 13.57.49.189:8080
  EU SRP-status:
    Title: EU SRP
    Template: SRP
    ThumbnailUrl: https://flagcdn.com/w2560/eu.png
    Color: '#003399'
    Servers:
    - Name: 1️⃣  Heavy Traffic I Public
      Address: 65.108.249.168:8080
    - Name: 2️⃣  Heavy Traffic I Public NON-DLC
      Address: 65.108.249.168:8081
  Drift-status:
    Title: Drift
    Template: emoji
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: 1️⃣  Traffic | SRP
      Address: 5.78.115.40:8083
    - Name: 2️⃣  Brooklyn Park
      Address: 5.78.115.40:8086
  Spec-status:
    Title: Tier 2 Spec
    Template: emoji
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: 1️⃣  Spec Cars | Heavy Traffic
      Address: 5.78.113.173:8080
  Sanbox-status:
    Title: Tier 3 Sandbox
    Template: emoji
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: 1️⃣  Sandbox | Heavy Traffic
      Address: 5.78.129.133:8081
  free-status:
    Title: Tier 3 Freeroam
    Template: emoji
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: 1️⃣ Union Island | Traffic
      Address: 5.78.129.133:8080
  preview-status:
    Title: Whiteline
    Template: SRP
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: 1️⃣ Whiteline | Heavy Traffic
      Address: 5.78.93.251:8080
  cops-status:
    Title: Cops and Robbers
    Template: SRP
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: 1️⃣ Cops and Robbers | Heavy Traffic
      Address: 5.78.93.251:8085
    - Name: 2️⃣ Hamburg Cops and Robbers | Heavy Traffic
      Address: 5.78.75.101:8081
  Hamburg-status:
    Title: Hamburg Public
    Template: SRP
    ThumbnailUrl: https://to-name.ru/images/historical-events/usa-united-states-america.jpg
    Color: '#003399'
    Servers:
    - Name: 1️⃣ Hamburg Public | Heavy Traffic
      Address: 5.78.75.101:8082
  German-status:
    Title: German Cars Public
    Template: SRP
    ThumbnailUrl: https://i.postimg.cc/pLPDrtWD/Flag-of-Germany-svg.png
    Color: '#003399'
    Servers:
    - Name: 1️⃣ German Cars Public | Heavy Traffic
      Address: 5.78.75.101:8080
  FDR-status:
    Title: FDR Public
    Template: SRP
    ThumbnailUrl: https://i.postimg.cc/yN24XK8G/Untitled-6.png
    Color: '#003399'
    Servers:
    - Name: 1️⃣ FDR Public US | Heavy Traffic
      Address: 5.78.103.54:8080
    - Name: 2️⃣ FDR Public EU | Heavy Traffic
      Address: 
# List of file-based user groups
FileBasedUserGroups:
- Name: blacklist
  Path: blacklist.txt
- Name: whitelist
  Path: whitelist.txt
# List of ranks for PatreonSafetyRatingPlugin
SafetyRatingRanks:
- Name: A
  Color: '#00FF00'
  MinimumRating: 3
  UserGroupName: 
- Name: B
  Color: 
  MinimumRating: 1
  UserGroupName: 
- Name: C
  Color: '#FF0000'
  MinimumRating: 0
  UserGroupName: 
# List of user groups based on the overtake leaderboard
OvertakeUserGroups:
- Name: Champion Overtake
  PreFilter: 
  PostFilter: Rank <= 1
- Name: Top 3 Overtake
  PreFilter: 
  PostFilter: Rank <= 3
- Name: Top 5 Overtake
  PreFilter: 
  PostFilter: Rank <= 5
- Name: Top 10 Overtake
  PreFilter: 
  PostFilter: Rank <= 10
- Name: Whiteline Certified
  PreFilter: 
  PostFilter: Score >= 2000000
- Name: Valid Whiteline
  PreFilter: 
  PostFilter: Score >= 1500000
- Name: Whiteline
  PreFilter: 
  PostFilter: Score >= 1000000
# List of user groups based on the timing leaderboard
TimingUserGroups: []
# List of extra columns shown on the timing leaderboard. Possible values: InputMethod, Weather, TrackGrip, TrackTemperature, AmbientTemperature, Tyre, GameTime, Sectors, CarChecksum, Shifter
TimingLeaderboardExtraColumns: []
